name: InfoSec White Paper Scraper

on:
  push:
    branches:
  schedule:
  - cron: 0 0 * * 1
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Scraper
      run: |
        python scrape.py
